spring.application.name=app_security


spring.datasource.url=jdbc:postgresql://localhost:5433/security_bank
spring.datasource.username=sam
spring.datasource.password=123456
spring.datasource.hiraki.connection-timeout=20000
spring.datasource.hiraki.maximum-pool-size=5